### ISSUE TITLE
Problem bei "Simple coding example"

### ISSUE THREAD

**Issue by LHA-QCS** [ZEISS-PiWeb/PiWeb-Calculated-Characteristics#75]
**4.0.1**

Hallo,
ich habe gerade versucht mir eine kleine Konsole Anwendung zu bauen und das "Example" zu testen, dabei werden mir immer die Typen "PathInformationDto",PathElementDto und AttributeDto als nicht gefunden (CS0246) bzw. als "im aktuellen Kontext nicht vorhanden" angezeigt.
Das Paket "CalculatedCharacteristics" habe ich über NuGet hinzugefügt.

Hab jetzt schon einige Zeit probiert, finde den Fehler aber nicht und finde auch nirgens passende Klassen dazu.

Ich bin dankbar für einen kurzen Tipp!

Gruß

Lars Hartwig
![Formel_Interpreter](https://github.com/ZEISS-PiWeb/PiWeb-Calculated-Characteristics/assets/123356168/911a2ed2-fdaf-4eb9-858e-bef94ebe87b5)

**Comment by nicoweh** [comment]
Hallo Herr Hartwig,
leider ist das Code-Beispiel, das Sie verwendet haben, noch nicht aktualisiert worden. Der Grund für die Fehler sind Änderungen in einem anderen Paket (PiWeb-Api), von dem Calculated-Characteristics abhängig ist.
Sie müssten entweder eine ältere Version des Nuget-Pakets "CalculatedCharacteristics" verwenden (max. 3.0.3) oder den Code etwas anpassen. Einige Klassen, wie PathInformation, PathElement und Attribute, enden nicht mehr auf Dto. Bitte beachten Sie auch den geänderten Namespace: Zeiss.PiWeb.Api.Core

**Comment by LHA-QCS** [comment]
Vielen Dank für die Antwort. Das bestätigt meinen Verdacht. Ich baue mir das entsprechend um.

**Comment by RonHeck** [comment]
https://github.com/ZEISS-PiWeb/PiWeb-Calculated-Characteristics/pull/91
